# Generated by Django 3.2.4 on 2021-12-01 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subscriptions',
            field=models.TextField(default=''),
        ),
    ]
