# Generated by Django 3.2.4 on 2021-12-02 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0002_alter_user_subscriptions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='subscriptions',
        ),
    ]
