# Generated by Django 3.2.4 on 2021-12-02 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0004_user_foreign_subscriptions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptions',
            name='no_of_members',
        ),
    ]
