# Generated by Django 3.2.4 on 2021-12-03 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0008_alter_user_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='number',
            field=models.TextField(),
        ),
    ]
