# Generated by Django 3.2.4 on 2021-12-03 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0009_alter_user_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptions',
            name='price',
            field=models.IntegerField(default=500),
        ),
    ]
